import { useState } from 'react';
import { invoke } from '@tauri-apps/api/core';

export default function Setup({ onComplete }) {
  const [step, setStep] = useState(1);
  const [wallet, setWallet] = useState('');
  const [pkMethod, setPkMethod] = useState('file');
  const [privateKey, setPrivateKey] = useState('');
  const [tgEnabled, setTgEnabled] = useState(false);
  const [tgToken, setTgToken] = useState('');
  const [tgChat, setTgChat] = useState('');
  const [maxLeverage, setMaxLeverage] = useState('10');
  const [maxDailyLoss, setMaxDailyLoss] = useState('200');
  const [coin, setCoin] = useState('BTC');
  const [balanceMsg, setBalanceMsg] = useState('');
  const [tgTestMsg, setTgTestMsg] = useState('');
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);

  const TOTAL_STEPS = 6;

  function validateWallet() {
    if (!/^0x[a-fA-F0-9]{40}$/.test(wallet.trim())) {
      setError('Invalid address. Must be 0x followed by 40 hex characters.');
      return false;
    }
    setError('');
    return true;
  }

  function validateKey() {
    if (!privateKey.trim()) {
      setError('Private key is required.');
      return false;
    }
    setError('');
    return true;
  }

  async function checkBalance() {
    setBalanceMsg('Checking...');
    try {
      const res = await fetch('https://api-ui.hyperliquid.xyz/info', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ type: 'spotClearinghouseState', user: wallet.trim() }),
      });
      const data = await res.json();
      const usdc = (data?.balances || []).find(b => b.coin === 'USDC');
      const bal = Number(usdc?.total ?? 0);
      if (bal > 0) {
        setBalanceMsg(`USDC balance: $${bal.toFixed(2)}`);
      } else {
        setBalanceMsg('No USDC balance detected. Deposit before starting the bot.');
      }
    } catch {
      setBalanceMsg('Could not check balance. You can continue and check later.');
    }
  }

  async function testTelegram() {
    setTgTestMsg('Sending...');
    try {
      const res = await fetch(`https://api.telegram.org/bot${tgToken.trim()}/sendMessage`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ chat_id: tgChat.trim(), text: 'HL Signalbot: setup test ping', disable_web_page_preview: true }),
      });
      const data = await res.json();
      setTgTestMsg(data.ok ? 'Test message sent! Check your Telegram.' : `Error: ${data.description || 'unknown'}`);
    } catch (e) {
      setTgTestMsg(`Failed: ${e?.message || e}`);
    }
  }

  async function handleSave() {
    setSaving(true);
    try {
      const config = {
        mode: 'live',
        wallet: { address: wallet.trim(), privateKeyPath: '~/.config/hl-signalbot/private_key' },
        market: { coin },
        signal: { pollMs: 20000, timeframe: { trend: '1h', trigger: '15m' }, emaTrendPeriod: 50, emaTriggerPeriod: 20, atrPeriod: 14, atrMult: 1.5, maxStopPct: 0.035 },
        risk: { maxLeverage: Number(maxLeverage) || 10, maxDailyLossUsd: Number(maxDailyLoss) || 200, cooldownSeconds: 10, riskPerTradePct: 0.03, marginUsePct: 0.75, minHoldSeconds: 120, reentryCooldownSeconds: 300, lossCooldownMinutes: 15, atrMinPct: 0.002 },
        exits: { stopLossPct: 0.10, maxMarginLossPct: 0.03, trailToBreakevenOnTp1: true, tp: [{ rMultiple: 1, closeFrac: 0.25 }, { rMultiple: 2, closeFrac: 0.25 }, { rMultiple: 3, closeFrac: 0.25 }], tpMinUsd: [10, 25, 60], runnerCloseFrac: 0.25, runnerExit: 'signal' },
        execution: { orderType: 'taker' },
        sdk: { disableAssetMapRefresh: true },
        display: { timezone: 'UTC' },
        telegram: { enabled: tgEnabled, channel: tgChat.trim() || '@your_channel', tokenPath: '~/.config/hl-signalbot/tg_token' },
      };

      // Get the config directory path for secret file references
      const configDir = await invoke('get_config_dir');
      const keyPath = `${configDir}/private_key`;
      const tgTokenPath = `${configDir}/tg_token`;

      // Update config to use actual absolute paths
      config.wallet.privateKeyPath = keyPath;
      if (tgEnabled) config.telegram.tokenPath = tgTokenPath;

      // Write config.json and .env (with restrictive perms via Rust)
      await invoke('write_bot_file', { filename: 'config.json', contents: JSON.stringify(config, null, 2) });

      const envLines = [
        '# HL Signalbot - generated by setup wizard',
        '',
        `HL_WALLET_ADDRESS=${wallet.trim()}`,
        pkMethod === 'env' ? `HL_PRIVATE_KEY=${privateKey.trim()}` : `HL_PRIVATE_KEY_PATH=${keyPath}`,
        '',
        `TG_ENABLED=${tgEnabled}`,
        tgEnabled ? `TG_CHAT=${tgChat.trim()}` : '',
        tgEnabled ? `TG_TOKEN_PATH=${tgTokenPath}` : '',
        '',
      ].filter(l => l !== undefined).join('\n');
      await invoke('write_bot_file', { filename: '.env', contents: envLines });

      // Write secret files with restrictive permissions (600 on Unix)
      if (pkMethod === 'file' && privateKey.trim()) {
        await invoke('write_secret_file', { path: keyPath, contents: privateKey.trim() + '\n' });
      }
      if (tgEnabled && tgToken.trim()) {
        await invoke('write_secret_file', { path: tgTokenPath, contents: tgToken.trim() + '\n' });
      }

      localStorage.setItem('bot_config', JSON.stringify(config));

      onComplete();
    } catch (e) {
      setError(e?.message || 'Failed to save configuration.');
    }
    setSaving(false);
  }

  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', background: 'var(--bg-primary)', padding: 24 }}>
      <div className="wizard">
        <div className="wizard-step">Step {step} of {TOTAL_STEPS}</div>

        {step === 1 && (
          <>
            <h2>Wallet Address</h2>
            <p className="step-desc">Enter the wallet address you use on Hyperliquid. This is the same address shown in the HL app top-right.</p>
            <div className="form-group">
              <input className="form-input mono" placeholder="0x..." value={wallet} onChange={e => setWallet(e.target.value)} />
              {error && <div className="error-msg">{error}</div>}
            </div>
            <div className="wizard-actions">
              <button className="btn btn-primary" onClick={() => validateWallet() && setStep(2)}>Next</button>
            </div>
          </>
        )}

        {step === 2 && (
          <>
            <h2>Private Key</h2>
            <p className="step-desc">Your key is stored locally and never uploaded. It is used to sign trades on Hyperliquid.</p>
            <div className="form-group">
              <label className="form-label">Storage method</label>
              <select className="form-input" value={pkMethod} onChange={e => setPkMethod(e.target.value)}>
                <option value="file">Save to encrypted file (recommended)</option>
                <option value="env">Store in environment variable</option>
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Private key (hex)</label>
              <input className="form-input mono" type="password" placeholder="64-character hex string" value={privateKey} onChange={e => setPrivateKey(e.target.value)} />
              <div className="form-hint">Find it in MetaMask: Settings &gt; Security &gt; Reveal Private Key</div>
              {error && <div className="error-msg">{error}</div>}
            </div>
            <div className="wizard-actions">
              <button className="btn btn-outline" onClick={() => setStep(1)}>Back</button>
              <button className="btn btn-primary" onClick={() => validateKey() && setStep(3)}>Next</button>
            </div>
          </>
        )}

        {step === 3 && (
          <>
            <h2>Fund Your Account</h2>
            <p className="step-desc">The bot needs USDC on Hyperliquid to trade. Deposit before starting.</p>
            <div className="info-box">
              <strong>How to deposit:</strong><br />
              1. Go to <a href="https://app.hyperliquid.xyz" target="_blank" rel="noreferrer">app.hyperliquid.xyz</a> and connect your wallet<br />
              2. Click <strong>"Deposit"</strong> in the top-right<br />
              3. Bridge or transfer USDC to Hyperliquid<br />
              4. Make sure USDC is in your <strong>Perps/Trading</strong> account (not Spot)<br />
              5. Check your balance below before continuing
            </div>
            <button className="btn btn-outline" onClick={checkBalance} style={{ marginBottom: 12 }}>Check Balance</button>
            {balanceMsg && <div className={balanceMsg.includes('$') ? 'success-msg' : 'warning-msg'}>{balanceMsg}</div>}
            <div className="wizard-actions">
              <button className="btn btn-outline" onClick={() => setStep(2)}>Back</button>
              <button className="btn btn-primary" onClick={() => setStep(4)}>Next</button>
            </div>
          </>
        )}

        {step === 4 && (
          <>
            <h2>Telegram Notifications</h2>
            <p className="step-desc">Get pinged on every trade open and close. Recommended but optional.</p>
            <div className="form-group">
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                <input type="checkbox" checked={tgEnabled} onChange={e => setTgEnabled(e.target.checked)} />
                <span>Enable Telegram pings</span>
              </label>
            </div>
            {tgEnabled && (
              <>
                <div className="info-box">
                  <strong>Setup steps:</strong><br />
                  1. Open Telegram, search for <strong>@BotFather</strong><br />
                  2. Send <strong>/newbot</strong>, choose a name and username<br />
                  3. Copy the bot token BotFather gives you<br />
                  4. Create a Telegram channel, add your bot as admin<br />
                  5. Enter the token and channel below
                </div>
                <div className="form-group">
                  <label className="form-label">Bot token</label>
                  <input className="form-input mono" placeholder="123456789:AAHdq..." value={tgToken} onChange={e => setTgToken(e.target.value)} />
                </div>
                <div className="form-group">
                  <label className="form-label">Channel @username or chat ID</label>
                  <input className="form-input" placeholder="@my_channel or -100..." value={tgChat} onChange={e => setTgChat(e.target.value)} />
                </div>
                <button className="btn btn-outline" onClick={testTelegram} disabled={!tgToken || !tgChat}>Send Test Message</button>
                {tgTestMsg && <div className={tgTestMsg.includes('sent') ? 'success-msg' : 'warning-msg'}>{tgTestMsg}</div>}
              </>
            )}
            <div className="wizard-actions">
              <button className="btn btn-outline" onClick={() => setStep(3)}>Back</button>
              <button className="btn btn-primary" onClick={() => setStep(5)}>Next</button>
            </div>
          </>
        )}

        {step === 5 && (
          <>
            <h2>Risk Parameters</h2>
            <p className="step-desc">These control how much the bot can risk. Defaults are conservative.</p>
            <div className="grid-2">
              <div className="form-group">
                <label className="form-label">Max leverage</label>
                <input className="form-input" type="number" value={maxLeverage} onChange={e => setMaxLeverage(e.target.value)} />
              </div>
              <div className="form-group">
                <label className="form-label">Max daily loss (USD)</label>
                <input className="form-input" type="number" value={maxDailyLoss} onChange={e => setMaxDailyLoss(e.target.value)} />
                <div className="form-hint">Bot halts if exceeded</div>
              </div>
            </div>
            <div className="form-group">
              <label className="form-label">Trading coin</label>
              <select className="form-input" value={coin} onChange={e => setCoin(e.target.value)}>
                <option value="BTC">BTC-PERP</option>
                <option value="ETH">ETH-PERP</option>
                <option value="SOL">SOL-PERP</option>
              </select>
            </div>
            <div className="wizard-actions">
              <button className="btn btn-outline" onClick={() => setStep(4)}>Back</button>
              <button className="btn btn-primary" onClick={() => setStep(6)}>Next</button>
            </div>
          </>
        )}

        {step === 6 && (
          <>
            <h2>Confirm Setup</h2>
            <p className="step-desc">Review your configuration before saving.</p>
            <div className="card">
              <div className="card-row"><span className="card-label">Wallet</span><span className="card-value mono" style={{ fontSize: 12 }}>{wallet}</span></div>
              <div className="card-row"><span className="card-label">Coin</span><span className="card-value">{coin}-PERP</span></div>
              <div className="card-row"><span className="card-label">Max leverage</span><span className="card-value">{maxLeverage}x</span></div>
              <div className="card-row"><span className="card-label">Max daily loss</span><span className="card-value">${maxDailyLoss}</span></div>
              <div className="card-row"><span className="card-label">Telegram</span><span className="card-value">{tgEnabled ? 'Enabled' : 'Disabled'}</span></div>
            </div>
            {error && <div className="error-msg">{error}</div>}
            <div className="wizard-actions">
              <button className="btn btn-outline" onClick={() => setStep(5)}>Back</button>
              <button className="btn btn-primary btn-lg" onClick={handleSave} disabled={saving}>
                {saving ? 'Saving...' : 'Save & Start'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
